"use client";
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { PolicyEditor } from "./policy-editor";
import { MessagesPanel } from "./messages-panel";
import { LegacyPanel } from "./legacy-panel";
import { formatMoney } from '../lib/frontend';
type Row=Record<string,unknown>;
type Requester=<T>(url:string,init?:RequestInit)=>Promise<T>;
export function BusinessPanel({request,role}:{request:Requester;role:string}){
 const [orders,setOrders]=useState<Row[]>([]);
 const [lots,setLots]=useState<Row[]>([]),[staff,setStaff]=useState<Row[]>([]),[refunds,setRefunds]=useState<Row[]>([]),[products,setProducts]=useState<Row[]>([]),[settings,setSettings]=useState<Row>({}),[preview,setPreview]=useState<Row|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const tasks:Promise<unknown>[]=[request<{orders:Row[]}>('/api/admin/orders?pageSize=100').then(x=>setOrders(x.orders)),request<{refunds:Row[]}>('/api/admin/refunds').then(x=>setRefunds(x.refunds))];if(role!=='finance')tasks.push(request<{lots:Row[]}>('/api/admin/inventory').then(x=>setLots(x.lots)),request<{products:Row[]}>('/api/admin/products').then(x=>setProducts(x.products)),request<{settings:Row}>('/api/admin/settings').then(x=>setSettings(x.settings)));if(role==='owner')tasks.push(request<{staff:Row[]}>('/api/admin/staff').then(x=>setStaff(x.staff)));await Promise.all(tasks);},[request,role]);
 useEffect(()=>{let cancelled=false;void load().catch(e=>{if(!cancelled)setNotice(e.message);});return()=>{cancelled=true;};},[load]);
 async function act(url:string,body:Row,method='POST'){setBusy(true);setNotice('');try{await request(url,{method,body:JSON.stringify(body)});await load();setNotice('Sačuvano.');}catch(e){setNotice(e instanceof Error?e.message:'Izmena nije uspela.');}finally{setBusy(false);}}
 const values=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget));};
 return <section className="admin-panel admin-form"><h2>Poslovanje</h2><p>Zalihe, zaposleni, pravila prodaje i povraćaji na jednom mestu.</p>{notice?<p role="status" className="admin-notice">{notice}</p>:null}
 {role!=='finance'?<>
 <details><summary>Zalihe i rokovi proizvoda</summary><p>Praćenje zaliha uključite pojedinačno u proizvodu. Paket rezerviše ukupnu količinu sa rokom koji pokriva poslednju dostavu.</p><form onSubmit={e=>{const v=values(e);void act('/api/admin/inventory',{...v,quantity:Number(v.quantity)});}}><div className="form-grid"><label className="field"><span>Proizvod</span><select name="productId" required>{products.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select></label><label className="field"><span>Broj serije</span><input name="lotNumber" required /></label><label className="field"><span>Važi do</span><input name="expiresOn" type="date" required /></label><label className="field"><span>Primljeno komada</span><input name="quantity" type="number" min="1" required /></label></div><button className="button small" disabled={busy}>Dodaj seriju</button></form><form onSubmit={e=>{const v=values(e);void act("/api/admin/inventory",{action:"replace",orderId:v.orderId});}}><label className="field"><span>Zameni rezervisanu seriju za porudžbinu (posle pauze ili isteka roka)</span><select name="orderId" required><option value="">Izaberite porudžbinu</option>{orders.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.order_number)} · {String(o.full_name??"")}</option>)}</select></label><button className="button secondary small" disabled={busy}>Rezerviši važeće serije</button></form><div className="table-scroll"><table><thead><tr><th>Proizvod / serija</th><th>Rok</th><th>Na stanju</th><th>Rezervisano</th><th>Slobodno</th></tr></thead><tbody>{lots.map(l=><tr key={String(l.id)}><td>{String(l.product_name)} · {String(l.lot_number)}</td><td>{String(l.expires_on)}</td><td>{Number(l.quantity)}</td><td>{Number(l.reserved)}</td><td>{Number(l.quantity)-Number(l.reserved)}</td></tr>)}</tbody></table></div></details>
 <PolicyEditor key={JSON.stringify(settings)} settings={settings} busy={busy} onSave={v=>void act('/api/admin/settings',v,'PATCH')} />
 </>:null}
 {role==='owner'?<details><summary>Zaposleni i pristup</summary><form onSubmit={e=>{const v=values(e);void act('/api/admin/staff',v);}}><div className="form-grid"><label className="field"><span>Ime zaposlenog</span><input name="fullName" required /></label><label className="field"><span>Email za prijavu</span><input name="email" type="email" required /></label><label className="field"><span>Početna lozinka (najmanje 12 znakova)</span><input name="password" type="password" minLength={12} autoComplete="new-password" required /></label><label className="field"><span>Pristup</span><select name="role"><option value="driver">Dostavljač — dostave</option><option value="finance">Finansije — računi i povraćaji</option><option value="manager">Menadžer — vođenje prodaje</option></select></label></div><button className="button small" disabled={busy}>Dodaj zaposlenog</button></form><ul>{staff.map(person=><li key={String(person.id)}>{String(person.full_name)} · {String(person.email)} · {String(person.role)} <button className="text-button" disabled={busy} onClick={()=>void act('/api/admin/staff',{id:person.id,isActive:!person.is_active})}>{person.is_active?'Ukini pristup':'Vrati pristup'}</button></li>)}</ul></details>:null}
 <MessagesPanel request={request} />
 {role!=="finance"?<LegacyPanel request={request} />:null}
 <details><summary>Ponovni pokušaj kartične naplate</summary><p>Neuspešna naplata može dobiti najviše tri pokušaja. Nepoznat ishod zahteva proveru u banci. Dok banka nije povezana, zahtevi ostaju na čekanju.</p><form onSubmit={e=>{const v=values(e);void act('/api/admin/payments',{action:'retry',orderId:v.orderId});}}><label className="field"><span>Porudžbina za ponovnu naplatu</span><select name="orderId" required><option value="">Izaberite porudžbinu</option>{orders.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.order_number)} · {String(o.full_name??"")} · {formatMoney(Number(o.total_minor)/100)}</option>)}</select></label><button className="button small" disabled={busy}>Stavi u red za naplatu</button></form></details>
 <details><summary>Povraćaji neisporučenih proizvoda</summary><p>Najpre proverite iznos. Odobrenje ne vraća novac dok servis za naplatu i fiskalnu korekciju nije povezan.</p><form onSubmit={async e=>{const v=values(e);setNotice('');try{setPreview(await request<Row>(`/api/admin/refunds?orderId=${encodeURIComponent(String(v.orderId))}`));}catch(e){setNotice(e instanceof Error?e.message:'Provera nije uspela.');}}}><label className="field"><span>Porudžbina za povraćaj</span><select name="orderId" required><option value="">Izaberite porudžbinu</option>{orders.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.order_number)} · {String(o.full_name??"")} · {formatMoney(Number(o.total_minor)/100)}</option>)}</select></label><button className="button small" disabled={busy}>Izračunaj povraćaj</button></form>{preview?<div><h3>Za povraćaj: {formatMoney(Number(preview.amountMinor)/100)}</h3><ul>{(preview.lines as Row[]).map(line=><li key={String(line.lineId)}>{String(line.productName)}: {Number(line.remaining)} neisporučenih komada</li>)}</ul><form onSubmit={e=>{const v=values(e);void act('/api/admin/refunds',{action:'request',orderId:(preview.order as Row).id,reason:v.reason,idempotencyKey:crypto.randomUUID()});}}><label className="field"><span>Razlog</span><input name="reason" required /></label><button className="button small" disabled={busy||!Number(preview.amountMinor)}>Napravi zahtev</button></form></div>:null}<ul className="list-clean">{refunds.map(r=><li className="admin-panel" key={String(r.id)}><strong>{String(r.full_name)} · {String(r.order_number)}</strong><p>{formatMoney(Number(r.amount_minor)/100)} · {String(r.status)} · {String(r.reason)}</p><div className="button-row">{r.status==='requested'?<button disabled={busy} className="button small" onClick={()=>void act('/api/admin/refunds',{id:r.id,expectedVersion:r.version,action:'approve'})}>Odobri</button>:null}{r.status==='approved'?<button disabled={busy} className="button small" onClick={()=>void act('/api/admin/refunds',{id:r.id,expectedVersion:r.version,action:'execute'})}>Izvrši preko povezanog servisa</button>:null}{['requested','approved'].includes(String(r.status))?<button disabled={busy} className="button secondary small" onClick={()=>void act('/api/admin/refunds',{id:r.id,expectedVersion:r.version,action:'reject'})}>Odbij zahtev</button>:null}</div>{r.payment_reference?<p>Potvrda: {String(r.payment_reference)} · {String(r.fiscal_reference)}</p>:null}</li>)}</ul></details>
 </section>;
}
