"use client";
import { useEffect, useState } from 'react';
type Row=Record<string,unknown>;
export function LegacyPanel({request}:{request:<T>(url:string,init?:RequestInit)=>Promise<T>}){
 const [orders,setOrders]=useState<Row[]>([]);
 useEffect(()=>{void request<{orders:Row[]}>("/api/admin/legacy").then(result=>setOrders(result.orders)).catch(()=>setOrders([]));},[request]);
 const [data,setData]=useState<{order:Row;lines:Row[]}|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <details><summary>Usaglašavanje starih plaćenih pretplata</summary><p>Unesite podatke iz postojećeg avansa i broj već uručenih komada. Ovaj postupak ne naplaćuje ponovo. Konačni račun može zahtevati dodatnu proveru originalnog fiskalnog zahteva.</p><form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{setData(await request(`/api/admin/legacy?orderId=${encodeURIComponent(String(form.get('orderId')))}`));}catch(e){setMessage(e instanceof Error?e.message:'Učitavanje nije uspelo.');}}}><label className="field"><span>Stara plaćena porudžbina</span><select name="orderId" required><option value="">Izaberite porudžbinu</option>{orders.map(order=><option key={String(order.id)} value={String(order.id)}>{String(order.order_number)} · {String(order.full_name)}</option>)}</select></label><button className="button small">Učitaj stavke</button></form>{data?<form onSubmit={async e=>{e.preventDefault();setBusy(true);const v=Object.fromEntries(new FormData(e.currentTarget));try{await request('/api/admin/legacy',{method:'POST',body:JSON.stringify({orderId:data.order.id,nextDeliveryDate:v.nextDeliveryDate,advanceInvoiceNumber:v.advanceInvoiceNumber,advanceTime:new Date(String(v.advanceTime)).toISOString(),confirmed:v.confirmed==='on',lines:data.lines.map(line=>({id:line.id,deliveredQuantity:Number(v[String(line.id)])}))})});setMessage('Pretplata je usaglašena. Preostali komadi su u rasporedu.');setData(null);}catch(e){setMessage(e instanceof Error?e.message:'Usaglašavanje nije uspelo.');}finally{setBusy(false);}}}><div className="form-grid"><label className="field"><span>Sledeća dostava</span><input name="nextDeliveryDate" type="date" required /></label><label className="field"><span>Broj izdatog avansnog računa</span><input name="advanceInvoiceNumber" required /></label><label className="field"><span>Vreme izdavanja avansa</span><input name="advanceTime" type="datetime-local" required /></label>{data.lines.map(line=><label className="field" key={String(line.id)}><span>{String(line.product_name)} — već uručeno komada</span><input name={String(line.id)} type="number" min="0" max={Number(line.quantity)*(line.cadence==='weekly'?4:2)} required defaultValue="0" /></label>)}</div><label><input name="confirmed" type="checkbox" required /> Proverio/la sam uplatu, avansni račun i ukupne količine.</label><button className="button small" disabled={busy}>Sačuvaj usaglašavanje</button></form>:null}{message?<p role="status">{message}</p>:null}</details>;
}
