"use client";
import { useCallback,useEffect,useState } from 'react';
type Row=Record<string,unknown>;
export function MessagesPanel({request}:{request:<T>(url:string,init?:RequestInit)=>Promise<T>}){
 const [messages,setMessages]=useState<Row[]>([]),[receipts,setReceipts]=useState<Row[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [m,r]=await Promise.all([request<{messages:Row[]}>('/api/admin/messages'),request<{recentReceipts:Row[]}>('/api/admin/integrations')]);setMessages(m.messages);setReceipts(r.recentReceipts);},[request]);
 useEffect(()=>{let active=true;void Promise.all([request<{messages:Row[]}>("/api/admin/messages"),request<{recentReceipts:Row[]}>("/api/admin/integrations")]).then(([m,r])=>{if(active){setMessages(m.messages);setReceipts(r.recentReceipts);}}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[request]);
 const statuses:Record<string,string>={simulated:'Lokalna simulacija',accepted:'Servis prihvatio',delivered:'Isporučeno serveru primaoca',bounced:'Odbijeno',complained:'Prijavljeno kao neželjeno',failed:'Greška',queued:'Čeka slanje',sending:'Slanje u toku',unknown:'Ishod čeka proveru',sent:'Poslato servisu',delivery_delayed:'Odložena isporuka'};
 return <details><summary>Slanje poruka i ponovno slanje računa</summary><p>Prihvatanje od servisa i potvrđena isporuka imaju odvojene statuse.</p>{notice?<p role="status">{notice}</p>:null}<ul className="list-clean">{receipts.filter(r=>r.status==='issued').map(r=><li className="summary-row" key={String(r.id)}><span>{String(r.order_number)} · {String(r.invoice_number)}</span><button className="button secondary small" disabled={busy} onClick={async()=>{setBusy(true);try{await request('/api/admin/integrations',{method:'POST',body:JSON.stringify({action:'resend_receipt',receiptId:r.id})});setNotice('Ponovno slanje je zakazano. Novi fiskalni račun nije izdat.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Slanje nije zakazano.');}finally{setBusy(false);}}}>Pošalji račun ponovo</button></li>)}</ul><div className="table-scroll"><table><thead><tr><th>Primalac</th><th>Poruka</th><th>Status</th></tr></thead><tbody>{messages.map(m=><tr key={String(m.id)}><td>{String(m.recipient)}<small> · {String(m.channel)}</small></td><td>{String(m.subject)}</td><td>{statuses[String(m.status)]??String(m.status)}</td></tr>)}</tbody></table></div></details>;
}
