import assert from 'node:assert/strict';
import { beforeEach, afterEach, test } from 'node:test';
import { register } from 'node:module';
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createDatabase } from './sqlite-d1.mjs';

const RealDate = Date, realFetch = globalThis.fetch;
let db, instant;
const env = {};
globalThis.__mlekoTestCloudflareEnv = env;
// This audit must never reach a bank, fiscal provider or real messaging service.
globalThis.fetch = async () => { throw new Error('External network is disabled in the functional audit'); };
register(new URL('./cloudflare-loader.mjs', import.meta.url));
const worker = (await import('../dist/server/index.js')).default;
const at = value => { instant = RealDate.parse(value); };
beforeEach(() => {
 Object.keys(env).forEach(key => delete env[key]);
 Object.assign(env, {APP_ENV:'local',APP_ORIGIN:'http://localhost',PAYMENT_MODE:'mock',BADI_MODE:'mock',EMAIL_MODE:'console',WHATSAPP_MODE:'disabled',ADMIN_LEGACY_ACCESS:'true',ADMIN_SECRET:'audit-only',PAYMENT_WEBHOOK_SECRET:'audit-webhook',CRON_SECRET:'audit-cron'});
 at('2026-12-30T10:00:00Z');
 globalThis.Date = class extends RealDate {constructor(...args){super(...(args.length?args:[instant]));}static now(){return instant;}};
 db = createDatabase(); env.DB = db;
 db.raw.exec("UPDATE products SET is_active=1, allow_subscription=1, price_minor=25000, subscription_price_minor=20000; UPDATE settings SET value_json='0' WHERE key IN ('deliveryFeeMinor','freeDeliveryThresholdMinor');");
});
afterEach(() => {db.close();globalThis.Date=RealDate;});
process.on('exit',()=>{globalThis.fetch=realFetch;});
async function api(path, data, {method=data===undefined?'GET':'POST', admin=false, cookie, key=randomUUID(), headers={}}={}) {
 const response=await worker.fetch(new Request('http://localhost'+path,{method,headers:{'content-type':'application/json',Origin:'http://localhost','Idempotency-Key':key,...(admin?{'x-admin-secret':env.ADMIN_SECRET}:{}),...(cookie?{cookie}:{}),...headers},...(method==='GET'||method==='DELETE'?{}:{body:JSON.stringify(data)})}),env,{waitUntil(){},passThroughOnException(){}});
 const text=await response.text();let body;try{body=JSON.parse(text);}catch{body=text;}
 return {status:response.status,body,headers:response.headers};
}
const ok=(result,status=200)=>{assert.equal(result.status,status,JSON.stringify(result.body));return result.body;};
const one=(sql,...args)=>db.raw.prepare(sql).get(...args);
const count=table=>one(`SELECT COUNT(*) n FROM ${table}`).n;
const line=(type='subscription',cadence='weekly',quantity=2)=>({productId:'prod_kravlje_1l',quantity,purchaseType:type,...(type==='subscription'?{cadence}:{})});
const customer=(extra={})=>({email:'audit@example.test',fullName:'Željko Audit',phone:'+381600000000',addressLine1:'Test ulica 1',city:'Beograd',postalCode:'11000',...extra});
const payload=(items=[line()],extra={})=>({items,customer:customer(),paymentMethod:'card',paymentToken:'mock-audit-token',deliveryDate:'2027-01-01',...extra});
const buy=async(items,extra)=>ok(await api('/api/checkout',payload(items,extra)),201);
function cookie(customerId=one('SELECT id FROM customers LIMIT 1').id) {
 const token=randomUUID();db.raw.prepare("INSERT INTO auth_tokens(id,customer_id,email,token_hash,kind,expires_at) VALUES(?,?,?,?,'session','2030-01-01T00:00:00Z')").run(randomUUID(),customerId,'audit@example.test',createHash('sha256').update(token).digest('base64url'));return 'mm_session='+token;
}
const mutate=async(id,action,extra={})=>api('/api/account/subscriptions/'+id,{action,expectedVersion:one('SELECT version FROM subscriptions WHERE id=?',id).version,...extra},{method:'PATCH',cookie:cookie()});
const setting=async(value)=>ok(await api('/api/admin/settings',value,{method:'PATCH',admin:true}));
const product=(extra={})=>({name:'Тест млеко Ž',slug:'audit-product',unitLabel:'6 × 1 L',priceMinor:35000,subscriptionPriceMinor:32000,description:'Opis proizvoda',...extra});
const newProduct=async(extra)=>ok(await api('/api/admin/products',product(extra),{admin:true}),201).product;
const promo=async(extra={})=>ok(await api('/api/admin/promos',{code:'AUDIT10',discountType:'percent',discountValue:10,...extra},{admin:true}),201).promo;
const quote=async(extra={})=>api('/api/cart',{items:[line('one_time','weekly',2)],deliveryDate:'2027-01-01',...extra});
const generate=async(date='2027-01-01')=>ok(await api('/api/admin/deliveries',{action:'generate',date},{admin:true}));
async function deliver(date,status='delivered'){at(date+'T10:00:00Z');const result=await generate(date);for(const order of result.orders)ok(await api('/api/admin/deliveries',{action:'complete',id:order.id,status},{admin:true}));return result;}

for (const [id, field, value, exposed=field] of [
 ['001','name','Novo mleko'],['002','description','Sveže mleko sa farme.'],['003','imageUrl','/images/mleko-i-mleko-logo-mark.png'],['005','subscriptionPriceMinor',31000],['006','unitLabel','500 ml'],['011','priceMinor',29000],['012','compareAtPriceMinor',49000],['125','name','Млеко čćšđž'],['133','sortOrder',0],['134','category','Jogurt'],['135','isFeatured',true],['097','fiscalTaxLabel','Е']
]) test(`Q${id}: catalog persists ${field} through admin API`,async()=>{
 const p=await newProduct();const changed=ok(await api('/api/admin/products/'+p.id,{[field]:value},{admin:true,method:'PATCH'})).product;assert.equal(changed[exposed],value);
 const listed=ok(await api('/api/admin/products',undefined,{admin:true})).products.find(x=>x.id===p.id);assert.equal(listed[exposed],value);
 if(id==='133'){const catalog=ok(await api('/api/products')).products;assert.equal(catalog[0].id,p.id);}
});
test('Q007 Q114: hidden product disappears and cannot be ordered',async()=>{const p=await newProduct();ok(await api('/api/admin/products/'+p.id,{isActive:false},{admin:true,method:'PATCH'}));assert.ok(!ok(await api('/api/products')).products.some(x=>x.id===p.id));ok(await api('/api/products/'+p.slug),404);ok(await quote({items:[{...line(),productId:p.id}]}),409);});
test('Q010 Q115: one-time-only product cannot be subscribed to',async()=>{const p=await newProduct({allowSubscription:false});ok(await quote({items:[{...line(),productId:p.id}]}),409);ok(await quote({items:[{...line('one_time'),productId:p.id}]}));});
for(const slug of ['bad slug','mleko_1','млеко'])test(`Q123: malformed product slug ${slug} is rejected`,async()=>{ok(await api('/api/admin/products',product({slug}),{admin:true}),422);assert.equal(count('products'),4);});
test('Q124: duplicate product slug is rejected without overwriting original',async()=>{const p=await newProduct();ok(await api('/api/admin/products',product(),{admin:true}),409);assert.equal(one('SELECT name FROM products WHERE id=?',p.id).name,p.name);});
test('Q131 Q136: missing photo remains optional and public catalog hides internal costs',async()=>{const p=await newProduct({imageUrl:null,costMinor:999,packagingCostMinor:88});const publicP=ok(await api('/api/products/'+p.slug)).product;assert.equal(publicP.imageUrl,null);for(const key of ['costMinor','packagingCostMinor','badiSku','fiscalTaxLabel'])assert.equal(Object.hasOwn(publicP,key),false);});
for(const imageUrl of ['http://example.test/a.png','javascript:alert(1)'])test(`Q132: unsafe photo scheme ${imageUrl.split(':')[0]} is rejected`,async()=>{ok(await api('/api/admin/products',product({imageUrl}),{admin:true}),422);});
test('Q137: deleting a purchased product archives it and preserves paid delivery',async()=>{const p=await newProduct();await buy([{...line(),productId:p.id}]);const removed=ok(await api('/api/admin/products/'+p.id,undefined,{admin:true,method:'DELETE'}));assert.equal(removed.archived,true);assert.equal(count('order_items'),1);assert.equal((await generate()).preparation[0].product_id,p.id);});
test('Q138 Q092: product changes leave audit entries, with shared rather than personal actor identity',async()=>{const p=await newProduct();ok(await api('/api/admin/products/'+p.id,{name:'Izmena'},{method:'PATCH',admin:true}));const rows=db.raw.prepare('SELECT action,actor_id FROM audit_log WHERE entity_id=?').all(p.id);assert.deepEqual(rows.map(x=>x.action).sort(),['product.created','product.updated']);assert.ok(rows.every(x=>x.actor_id==='local-admin'));});
for(const type of ['percent','fixed'])test(`Q014 Q015: ${type} promo has independently verified exact total`,async()=>{await promo({discountType:type,discountValue:type==='percent'?10:7000});const result=ok(await quote({promoCode:'AUDIT10'}));assert.equal(result.subtotalMinor,50000);assert.equal(result.discountMinor,type==='percent'?5000:7000);assert.equal(result.totalMinor,type==='percent'?45000:43000);});
for(const [id,extra] of [['116',{endsAt:'2026-12-29T00:00:00Z'}],['117',{startsAt:'2026-12-31T00:00:00Z'}],['118',{minimumOrderMinor:50001}],['016',{usageLimit:0}]])test(`Q${id}: ineligible promo cannot discount the cart`,async()=>{await promo(extra);ok(await quote({promoCode:'AUDIT10'}),422);assert.equal(count('orders'),0);});
test('Q019 Q119 Q120: promo combines with catalog sale, normalizes case and never discounts delivery',async()=>{await setting({deliveryFeeMinor:35000});await promo({discountType:'fixed',discountValue:999999});const result=ok(await quote({promoCode:' audit10 '}));assert.equal(result.discountMinor,50000);assert.equal(result.totalMinor,35000);});
test('Q018: initial promo is not silently renewed on the next package',async()=>{await promo();const purchase=await buy(undefined,{promoCode:'AUDIT10'});for(const date of ['2027-01-01','2027-01-08','2027-01-15','2027-01-22'])await deliver(date);ok(await api('/api/jobs/billing',{month:'2027-02'},{admin:true}));const renewed=one('SELECT discount_minor,promo_code,total_minor FROM orders WHERE id != ?',purchase.order.id);assert.equal(renewed.discount_minor,0);assert.equal(renewed.promo_code,null);assert.equal(renewed.total_minor,160000);});
for(let mask=1;mask<8;mask++)test(`Q023 Q024 Q025 Q112: cart combination ${mask} preserves all purchased units`,async()=>{const options=[line('one_time','weekly',1),line('subscription','weekly',2),line('subscription','biweekly',3)];const items=options.filter((_,i)=>mask&(1<<i));const q=ok(await quote({items}));const expected=items.reduce((sum,item)=>sum+(item.purchaseType==='one_time'?25000*item.quantity:20000*item.quantity*(item.cadence==='weekly'?4:2)),0);assert.equal(q.totalMinor,expected);const purchase=await buy(items);assert.equal(purchase.order.totalMinor,expected);assert.equal(count('order_items'),items.length);if(mask>1){assert.equal(count('package_lines'),items.length);for(const date of ['2027-01-01','2027-01-08','2027-01-15','2027-01-22'])await deliver(date);assert.equal(one("SELECT SUM(quantity) n FROM delivery_items di JOIN delivery_orders dor ON dor.id=di.delivery_order_id WHERE dor.status='delivered'").n,items.reduce((sum,item)=>sum+item.quantity*(item.purchaseType==='one_time'?1:item.cadence==='weekly'?4:2),0));}});
test('Q021 Q022 Q101: guest checkout uses RSD and rejects missing mandatory contact fields',async()=>{for(const field of ['email','fullName','phone','addressLine1','city','postalCode']){const input=payload();delete input.customer[field];ok(await api('/api/checkout',input),422);}const order=await buy();assert.equal(order.order.currency,'RSD');assert.equal(count('customers'),1);});
test('Q030: manual cash order without email is persisted and included in preparation',async()=>{const input=payload([line('one_time')],{paymentMethod:'cash',notify:false});delete input.customer.email;const result=ok(await api('/api/admin/orders',input,{admin:true}),201);assert.equal(result.order.paymentStatus,'pending');assert.equal((await generate()).preparation[0].total_quantity,2);});
test('Q037: separate checkouts can create independent subscriptions for the same customer',async()=>{await buy();await buy([line('subscription','biweekly')]);assert.equal(count('customers'),1);assert.equal(count('subscriptions'),2);assert.equal(count('subscription_packages'),2);});
for(const quantity of [0,-1,1.5,101,'2'])test(`Q106 Q107: invalid item quantity ${JSON.stringify(quantity)} is rejected`,async()=>{ok(await api('/api/checkout',payload([line('one_time','weekly',quantity)])),422);assert.equal(count('orders'),0);});
test('Q106: 100 units is the accepted per-line maximum',async()=>{assert.equal(ok(await quote({items:[line('one_time','weekly',100)]})).subtotalMinor,2500000);});
test('Q108: empty and more-than-50-line carts are rejected',async()=>{for(const items of [[],Array.from({length:51},()=>line())])ok(await api('/api/checkout',payload(items)),422);assert.equal(count('orders'),0);});
test('Q109 Q110: unknown product, purchase type or cadence cannot create an order',async()=>{for(const [item,status] of [[{...line(),productId:'missing'},409],[{...line(),purchaseType:'gift'},422],[{...line(),cadence:'daily'},422]])ok(await api('/api/checkout',payload([item])),status);assert.equal(count('orders'),0);});
test('Q111: duplicate cart rows conserve quantities rather than silently dropping a row',async()=>{await buy([line('one_time'),line('one_time')]);const next=await generate();assert.equal(next.preparation[0].total_quantity,4);assert.equal(count('order_items'),2);});
test('Q113: forged browser prices and totals are ignored',async()=>{const result=await buy([{...line('one_time'),unitPriceMinor:1,lineTotalMinor:1}],{totalMinor:1});assert.equal(result.order.totalMinor,50000);});
test('Q148 Q149: free shipping boundary is exact and later fee changes preserve purchased invoice',async()=>{await setting({deliveryFeeMinor:35000,freeDeliveryThresholdMinor:50000});assert.equal(ok(await quote()).deliveryFeeMinor,0);assert.equal(ok(await quote({items:[line('one_time','weekly',1)]})).deliveryFeeMinor,35000);const paid=await buy();await setting({deliveryFeeMinor:99999});assert.equal(one('SELECT total_minor FROM orders WHERE id=?',paid.order.id).total_minor,paid.order.totalMinor);});
test('Q151: configured weekend delivery is accepted, an unconfigured weekday is rejected',async()=>{await setting({deliveryWeekdays:[6]});ok(await quote({deliveryDate:'2027-01-02'}));ok(await quote({deliveryDate:'2027-01-01'}),422);});
test('Q051 Q052 Q053 Q054: preparation totals equal the sum of customer line quantities',async()=>{await buy([line('one_time','weekly',1),line('subscription','weekly',3)]);await buy([line('subscription','biweekly',2)],{customer:customer({email:'second@example.test',fullName:'Drugi Kupac'})});const result=ok(await api('/api/admin/delivery-preview?date=2027-01-01',undefined,{admin:true}));assert.equal(result.preparation[0].total_quantity,6);assert.equal(result.orders.reduce((sum,x)=>sum+x.items.reduce((n,i)=>n+i.quantity,0),0),6);assert.equal(result.orders.filter(x=>x.subscription_id).length,2);assert.equal(result.orders.filter(x=>!x.subscription_id).length,1);assert.ok(JSON.stringify(result).includes('Drugi Kupac'));});
test('Q078: resending an issued receipt queues email without issuing a second fiscal document',async()=>{await buy();const receipt=one("SELECT * FROM fiscal_receipts WHERE status='issued'");const countBefore=count('fiscal_receipts');ok(await api('/api/admin/integrations',{action:'resend_receipt',receiptId:receipt.id},{admin:true}));assert.equal(count('fiscal_receipts'),countBefore);assert.equal(one("SELECT COUNT(*) n FROM outbox WHERE idempotency_key LIKE 'resend:%'").n,1);ok(await api('/api/admin/integrations',{action:'resend_receipt',receiptId:'missing'},{admin:true}),409);});
test('Q082 Q083: customer account shows purchased quantity, progress and next date',async()=>{const purchase=await buy();await deliver('2027-01-01');const account=ok(await api('/api/account',undefined,{cookie:cookie()}));const s=account.subscriptions.find(x=>x.id===purchase.subscription.id);assert.equal(s.nextDeliveryDate,'2027-01-08');assert.equal(s.currentPackage[0].delivered,1);assert.equal(s.currentPackage[0].required_deliveries,4);assert.equal(s.currentPackage[0].quantity,2);});
test('Q094: admin order search finds name, phone and order number without returning another customer',async()=>{const purchase=await buy();await buy(undefined,{customer:customer({email:'other@example.test',fullName:'Drugi',phone:'0619999999'})});for(const q of ['Željko','+381600000000',purchase.order.orderNumber]){const result=ok(await api('/api/admin/orders?q='+encodeURIComponent(q),undefined,{admin:true}));assert.equal(result.orders.length,1);assert.equal(result.orders[0].id,purchase.order.id);}});
test('Q095: dashboard counts paid revenue independently from pending cash orders',async()=>{const paid=await buy();await buy([line('one_time')],{paymentMethod:'cash'});const d=ok(await api('/api/admin/dashboard',undefined,{admin:true}));assert.equal(d.revenue.paid_revenue_minor,paid.order.totalMinor);});
test('Q155 Q156 Q159: completion rejects unprepared and future deliveries, then cannot reverse handover',async()=>{await buy();const future=await generate();ok(await api('/api/admin/deliveries',{action:'complete',id:future.orders[0].id,status:'delivered'},{admin:true}),409);const locked=ok(await api('/api/admin/deliveries',{action:'lock',date:'2027-01-01',force:true},{admin:true}));future.orders=locked.orders;ok(await api('/api/admin/deliveries',{action:'complete',id:future.orders[0].id,status:'delivered'},{admin:true}),409);at('2027-01-01T10:00:00Z');ok(await api('/api/admin/deliveries',{action:'complete',id:future.orders[0].id,status:'delivered'},{admin:true}));ok(await api('/api/admin/deliveries',{action:'complete',id:future.orders[0].id,status:'failed'},{admin:true}),409);});
test('Q162: failed biweekly delivery retries 14 days later and does not consume entitlement',async()=>{await buy([line('subscription','biweekly')]);await deliver('2027-01-01','failed');assert.equal((await generate('2027-01-08')).orders.length,0);await deliver('2027-01-15');assert.equal(count('fiscal_receipts'),1);await deliver('2027-01-29');assert.equal(one("SELECT COUNT(*) n FROM fiscal_receipts WHERE kind='final'").n,1);});
test('Q163: skipping mixed rhythms moves only to an actual next cadence date',async()=>{const purchase=await buy([line('subscription','weekly',2),line('subscription','biweekly',3)]);ok(await mutate(purchase.subscription.id,'skip_next'));assert.equal((await generate()).orders.length,0);assert.equal((await generate('2027-01-08')).preparation[0].total_quantity,2);assert.equal((await generate('2027-01-15')).preparation[0].total_quantity,5);});
test('Q164 Q165: calendar pause clamps January 31 to April 30 and rejects impossible dates',async()=>{at('2027-01-31T10:00:00Z');const p=await buy(undefined,{deliveryDate:'2027-02-02'});const account=ok(await api('/api/account',undefined,{cookie:cookie()}));assert.equal(account.subscriptions[0].maxPauseUntil,'2027-04-30');ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-02-30'}),422);ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-05-01'}),422);ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-04-30'}));});
test('Q166: skipping an unpaid package keeps all entitlements after payment',async()=>{const p=await buy(undefined,{paymentMethod:'cash'});ok(await mutate(p.subscription.id,'skip_next'));ok(await api('/api/admin/orders',{id:p.order.id,paymentStatus:'paid'},{admin:true,method:'PATCH'}));assert.equal((await generate()).orders.length,0);assert.equal((await generate('2027-01-08')).preparation[0].total_quantity,2);assert.equal(one('SELECT required_deliveries FROM package_lines').required_deliveries,4);});
for(const action of ['skip_next','pause'])test(`Q171 Q172: next-only addon follows ${action} and is not duplicated`,async()=>{const p=await buy();ok(await mutate(p.subscription.id,'add_next_only',{productId:'prod_jogurt_1l',quantity:1}));ok(await mutate(p.subscription.id,action,action==='pause'?{pauseUntil:'2027-02-01'}:{}));const next=one('SELECT next_delivery_date FROM subscriptions').next_delivery_date;assert.equal(one('SELECT delivery_date FROM next_delivery_addons').delivery_date,next);assert.equal(one("SELECT delivery_date FROM orders WHERE kind='adjustment'").delivery_date,next);assert.equal((await generate()).orders.length,0);assert.equal((await generate(next)).preparation.find(x=>x.product_id==='prod_jogurt_1l').total_quantity,1);});
test('Q174: inactive product prevents renewal without charging again',async()=>{await buy();for(const date of ['2027-01-01','2027-01-08','2027-01-15','2027-01-22'])await deliver(date);ok(await api('/api/admin/products/prod_kravlje_1l',{isActive:false},{admin:true,method:'PATCH'}));const response=ok(await api('/api/jobs/billing',{month:'2027-02'},{admin:true}));assert.equal(response.results[0].skipped,'product_unavailable');assert.equal(count('orders'),1);});
test('Q176: legacy monthly invoice is not silently charged as a new package',async()=>{await buy();db.raw.exec('DELETE FROM package_lines; DELETE FROM subscription_packages;');const response=ok(await api('/api/jobs/billing',{month:'2027-02'},{admin:true}));assert.equal(response.results[0].skipped,'legacy_review_required');assert.equal(count('orders'),1);});
test('Q177 Q178: another customer and expired sessions cannot access subscription changes',async()=>{const a=await buy();await buy(undefined,{customer:customer({email:'other@example.test'})});const other=one("SELECT id FROM customers WHERE email='other@example.test'").id;ok(await api('/api/account/subscriptions/'+a.subscription.id,{action:'cancel',expectedVersion:1},{method:'PATCH',cookie:cookie(other)}),404);const session=cookie();db.raw.exec("UPDATE auth_tokens SET expires_at='2020-01-01'");ok(await api('/api/account',undefined,{cookie:session}),401);});
test('Q184: malformed email is rejected before customer creation',async()=>{ok(await api('/api/checkout',payload(undefined,{customer:customer({email:'not-email'})})),422);assert.equal(count('customers'),0);});
test('Q188 Q189 Q190: payment webhook authenticates, deduplicates, and protects paid package state',async()=>{const p=await buy(undefined,{paymentMethod:'cash'}),event={eventId:randomUUID(),orderId:p.order.id,status:'paid'};ok(await api('/api/webhooks/payments',event,{headers:{'x-webhook-secret':'bad'}}),401);const options={headers:{'x-webhook-secret':env.PAYMENT_WEBHOOK_SECRET}};ok(await api('/api/webhooks/payments',event,options));assert.equal(ok(await api('/api/webhooks/payments',event,options)).duplicate,true);ok(await api('/api/admin/orders',{id:p.order.id,paymentStatus:'pending'},{admin:true,method:'PATCH'}),409);assert.equal(count('webhook_events'),1);assert.equal(count('fiscal_receipts'),1);});
test('Q192: completed package waits for missing advance rather than issuing a final alone',async()=>{env.FISCAL_PROVIDER='fiscomm';env.FISCOMM_MODE='disabled';await buy([line('subscription','biweekly')]);await deliver('2027-01-01');await deliver('2027-01-15');assert.equal(one("SELECT COUNT(*) n FROM fiscal_receipts WHERE status='issued'").n,0);assert.equal(one("SELECT last_error_code FROM fiscal_receipts WHERE kind='final'").last_error_code,'ADVANCE_NOT_ISSUED');});
for(const [id,bytes,type,status] of [['127',new Uint8Array(2000001),'image/png',422],['129',new TextEncoder().encode('<svg onload="alert(1)"/>'),'image/svg+xml',422],['130',new TextEncoder().encode('<script>alert(1)</script>'),'image/png',422],['128',readFileSync(new URL('../public/images/mleko-i-mleko-logo-mark.png',import.meta.url)),'image/png',201]])test(`Q${id}: uploaded ${type} with ${bytes.length} bytes validates content and size`,async()=>{const form=new FormData();form.append('image',new File([bytes],'audit-image',{type}));const response=await worker.fetch(new Request('http://localhost/api/admin/product-images',{method:'POST',headers:{'x-admin-secret':env.ADMIN_SECRET,Origin:'http://localhost'},body:form}),env,{waitUntil(){},passThroughOnException(){}});assert.equal(response.status,status);if(status===201){const {url}=await response.json();const image=await worker.fetch(new Request('http://localhost'+url),env,{waitUntil(){},passThroughOnException(){}});assert.equal(image.headers.get('content-type'),'image/png');assert.equal(image.headers.get('x-content-type-options'),'nosniff');assert.equal((await image.arrayBuffer()).byteLength,bytes.length);}else assert.equal(count('product_images'),0);});

// Reproductions are marked TODO only after confirming the current behavior.
// Their failing assertions remain executable and visible in the audit report.
test('Q047: early resume should restore the first editable delivery, not the old pause-end date',async()=>{const p=await buy();ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-03-01'}));ok(await mutate(p.subscription.id,'resume'));assert.equal(one('SELECT next_delivery_date FROM subscriptions').next_delivery_date,'2027-01-01');});
test('Q104: a second guest order should not rewrite an earlier open order delivery address',async()=>{const first=await buy([line('one_time')]);await buy([line('one_time')],{customer:customer({addressLine1:'Druga adresa 22'})});const detail=ok(await api('/api/admin/orders/'+first.order.id,undefined,{admin:true}));assert.equal(detail.order.address_line_1,'Test ulica 1');});
test('Q046: extending a paused subscription preserves purchased units',async()=>{const p=await buy();ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-02-01'}));const response=await mutate(p.subscription.id,'pause',{pauseUntil:'2027-03-01'});ok(response);assert.equal(one('SELECT pause_until FROM subscriptions').pause_until,'2027-03-01');});
test('Q126: product description markup is escaped in server rendered HTML',async()=>{const p=await newProduct({description:'<script>window.auditInjected=true</script>'});const response=ok(await api('/proizvodi/'+p.slug));assert.ok(response.includes('&lt;script&gt;'));assert.ok(!response.includes('<script>window.auditInjected=true</script>'));});
test('Q093: competing order updates accept only one original version',async()=>{const p=await buy([line('one_time')],{paymentMethod:'cash'});const before=one('SELECT updated_at FROM orders WHERE id=?',p.order.id);const outcomes=await Promise.all(['Prva','Druga'].map(customerNote=>api('/api/admin/orders',{id:p.order.id,expectedUpdatedAt:before.updated_at,customerNote},{admin:true,method:'PATCH'})));assert.deepEqual(outcomes.map(x=>x.status).sort(),[200,409]);assert.ok(['Prva','Druga'].includes(one('SELECT customer_note FROM orders WHERE id=?',p.order.id).customer_note));});
test('Q167 Q169 Q170: future configuration merges matching items and cannot restart cancelled renewal or alter paid cadence',async()=>{const p=await buy();ok(await mutate(p.subscription.id,'cancel'));ok(await mutate(p.subscription.id,'add_item',{productId:'prod_kravlje_1l',quantity:1,cadence:'weekly'}));assert.equal(count('subscription_items'),1);assert.equal(one('SELECT quantity FROM subscription_items').quantity,3);ok(await mutate(p.subscription.id,'slow_down'));assert.equal(one('SELECT cadence FROM subscription_items').cadence,'biweekly');assert.equal(one('SELECT renewal_enabled FROM subscriptions').renewal_enabled,0);assert.equal((await generate('2027-01-08')).preparation[0].total_quantity,2);assert.equal(one('SELECT cadence FROM order_items').cadence,'weekly');});
test('Q173: stopping paid-package renewal retains and delivers the purchased next-only addon',async()=>{const p=await buy();ok(await mutate(p.subscription.id,'add_next_only',{productId:'prod_jogurt_1l',quantity:1}));ok(await mutate(p.subscription.id,'cancel'));assert.equal(one('SELECT cancelled_at FROM next_delivery_addons').cancelled_at,null);const delivered=await deliver('2027-01-01');assert.equal(delivered.preparation.find(x=>x.product_id==='prod_jogurt_1l').total_quantity,1);assert.ok(one('SELECT consumed_at FROM next_delivery_addons').consumed_at);});
test('Q185: cross-origin customer mutation is rejected without state change',async()=>{const p=await buy();ok(await api('/api/account/subscriptions/'+p.subscription.id,{action:'cancel',expectedVersion:1},{method:'PATCH',cookie:cookie(),headers:{Origin:'https://other.example.test'}}),403);assert.equal(one('SELECT renewal_enabled FROM subscriptions').renewal_enabled,1);});
test('Q186: real admin session rejects wrong password, missing token and expired token',async()=>{env.ADMIN_EMAIL='admin@example.test';env.ADMIN_PASSWORD='audit-password-only';delete env.ADMIN_LEGACY_ACCESS;ok(await api('/api/admin/orders'),403);ok(await api('/api/admin/access',{email:env.ADMIN_EMAIL,password:'wrong'}),403);const login=ok(await api('/api/admin/access',{email:env.ADMIN_EMAIL,password:env.ADMIN_PASSWORD}));const headers={authorization:'Bearer '+login.sessionToken};ok(await api('/api/admin/orders',undefined,{headers}));at('2026-12-31T10:00:00Z');ok(await api('/api/admin/orders',undefined,{headers}),403);});
test('Q187: account, order details and readiness do not expose provider tokens or credentials',async()=>{const p=await buy([line('one_time')]);const session=cookie();for(const endpoint of ['/api/account','/api/account/orders/'+p.order.id]){const result=ok(await api(endpoint,undefined,{cookie:session}));assert.doesNotMatch(JSON.stringify(result),/mock-audit-token|payment_provider_ref|cost_minor|ADMIN_SECRET|FISCOMM_API_KEY/);}const diagnostics=ok(await api('/api/admin/commerce-readiness',undefined,{admin:true}));assert.doesNotMatch(JSON.stringify(diagnostics),/audit-webhook|audit-only|mock-audit-token/);assert.equal(diagnostics.payment.cardAvailable,false);});
for (const [file,mime] of [['catalog/kravlje-mleko.jpg','image/jpeg'],['catalog/kravlje-mleko.webp','image/webp']]) test(`Q128: ${mime} upload round-trips a real catalog asset`,async()=>{
 const bytes=readFileSync(new URL('../public/images/'+file,import.meta.url)),form=new FormData();form.append('image',new File([bytes],file,{type:mime}));
 const uploaded=await worker.fetch(new Request('http://localhost/api/admin/product-images',{method:'POST',headers:{'x-admin-secret':env.ADMIN_SECRET,Origin:'http://localhost'},body:form}),env,{waitUntil(){},passThroughOnException(){}});assert.equal(uploaded.status,201);
 const {url}=await uploaded.json();const response=await worker.fetch(new Request('http://localhost'+url),env,{waitUntil(){},passThroughOnException(){}});assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),mime);assert.deepEqual(Buffer.from(await response.arrayBuffer()),bytes);
});
test('Q085: later checkout cannot rewrite a locked delivery address snapshot',async()=>{
 await buy([line('one_time')]);await generate();const locked=ok(await api('/api/admin/deliveries',{action:'lock',date:'2027-01-01',force:true},{admin:true}));
 assert.equal(locked.orders[0].customer_snapshot.addressLine1,'Test ulica 1');
 await buy([line('one_time')],{deliveryDate:'2027-01-08',customer:customer({addressLine1:'Druga adresa 22'})});
 const saved=ok(await api('/api/admin/deliveries?date=2027-01-01',undefined,{admin:true}));assert.equal(saved.orders[0].customer_snapshot.addressLine1,'Test ulica 1');
});

// Extended implementation regression suite — real HTTP handlers and isolated SQLite.
test('Q004 Q142: gallery and nutrition survive edit and public retrieval',async()=>{const p=await newProduct({gallery:['/images/one.png','https://example.test/two.png'],ingredients:'Mleko',allergens:'Mleko',nutrition:{Proteini:'3.2 g'}});const got=ok(await api('/api/products/'+p.slug)).product;assert.deepEqual(got.gallery,p.gallery);assert.equal(got.nutrition.Proteini,'3.2 g');ok(await api('/api/admin/products/'+p.id,{gallery:['javascript:alert(1)']},{admin:true,method:'PATCH'}),422);});
test('Q013: scheduled product prices start and expire without changing purchased snapshot',async()=>{const p=await newProduct({salePriceMinor:15000,saleSubscriptionPriceMinor:10000,saleStartsAt:'2026-12-30T11:00:00Z',saleEndsAt:'2026-12-30T13:00:00Z'});assert.equal(ok(await quote({items:[{...line('one_time'),productId:p.id}]})).totalMinor,70000);at('2026-12-30T12:00:00Z');const order=await buy([{...line('one_time'),productId:p.id}]);assert.equal(order.order.totalMinor,30000);at('2026-12-30T14:00:00Z');assert.equal(ok(await quote({items:[{...line('one_time'),productId:p.id}]})).totalMinor,70000);assert.equal(one('SELECT total_minor FROM orders WHERE id=?',order.order.id).total_minor,30000);});
test('Q139: cloned product has independent identity and starts unpublished',async()=>{const p=await newProduct({gallery:['/one.png'],allergens:'Mleko'});const copy=ok(await api('/api/admin/products/'+p.id,{}, {admin:true}),201).product;assert.notEqual(copy.id,p.id);assert.notEqual(copy.slug,p.slug);assert.equal(copy.isActive,false);assert.deepEqual(copy.gallery,p.gallery);});
test('Q017 Q122: first-order and per-customer promo limits enforced on checkout',async()=>{await promo({firstPurchaseOnly:true,perCustomerLimit:1});await buy([line('one_time')],{promoCode:'AUDIT10'});ok(await api('/api/checkout',payload([line('one_time')],{promoCode:'AUDIT10'})),422);assert.equal(count('orders'),1);assert.equal(count('order_promotions'),1);});
test('Q121: explicit stacking uses remaining subtotal, forbidden combinations rejected',async()=>{await promo({stackable:true});await promo({code:'SECOND',stackable:true,discountValue:20});assert.equal(ok(await quote({promoCode:'AUDIT10,SECOND'})).discountMinor,14000);await promo({code:'EXCLUSIVE'});ok(await quote({promoCode:'AUDIT10,EXCLUSIVE'}),422);});
test('Q105: minimum order enforced server-side even when client skips quote',async()=>{await setting({minimumOrderMinor:50001});ok(await api('/api/checkout',payload([line('one_time')])),422);assert.equal(count('orders'),0);assert.equal(ok(await quote()).minimumOrderMet,false);});
test('Q143 Q144: new city works through checkout and holiday cannot be booked',async()=>{await setting({serviceRegions:[{city:'Niš',postalCodes:['18000']}],holidays:['2027-01-01']});ok(await api('/api/checkout',payload([line('one_time')],{customer:customer({city:'Niš',postalCode:'18000'})})),422);await setting({holidays:[]});const result=await buy([line('one_time')],{customer:customer({city:'Niš',postalCode:'18000'})});assert.ok(result.order.id);assert.equal((await generate()).orders[0].customer_snapshot.city,'Niš');});
test('Q150: slot capacity cannot be exceeded and unlisted slot is rejected',async()=>{await setting({deliverySlots:[{id:'morning',label:'08–12',capacity:1}]});ok(await api('/api/checkout',payload([line('one_time')])),422);await buy([line('one_time')],{slotId:'morning'});ok(await api('/api/checkout',payload([line('one_time')],{slotId:'morning'})),409);assert.equal(count('orders'),1);});
test('Q102 Q103 Q104: billing and shipping snapshots remain distinct across repeated guest purchases',async()=>{const a=await buy([line('one_time')],{billing:{companyName:'Test firma',taxId:'123456789',addressLine1:'Račun 10',city:'Novi Sad',postalCode:'21000'}});await buy([line('one_time')],{customer:customer({addressLine1:'Nova dostava 33'})});const saved=one('SELECT * FROM orders WHERE id=?',a.order.id);assert.equal(JSON.parse(saved.billing_json).addressLine1,'Račun 10');assert.equal(JSON.parse(saved.shipping_json).addressLine1,'Test ulica 1');const route=await generate();assert.deepEqual(route.orders.map(o=>o.customer_snapshot.addressLine1).sort(),['Nova dostava 33','Test ulica 1']);});
test('Q084: authenticated profile changes do not rewrite earlier order addresses',async()=>{const order=await buy([line('one_time')]);ok(await api('/api/account',{phone:'+381611111111',addressLine1:'Moj profil 9'},{method:'PATCH',cookie:cookie()}));assert.equal(one('SELECT phone FROM customers').phone,'+381611111111');assert.equal(ok(await api('/api/admin/orders/'+order.order.id,undefined,{admin:true})).order.address_line_1,'Test ulica 1');});
test('Q060: partial quantity requires a fifth visit and exactly one final fiscal event',async()=>{const order=await buy();at('2027-01-01T10:00:00Z');const first=await generate();const delivery=first.orders[0];ok(await api('/api/admin/deliveries',{action:'complete',id:delivery.id,status:'delivered',items:delivery.items.map(item=>({id:item.id,deliveredQuantity:1}))},{admin:true}));assert.equal(one('SELECT delivered_quantity FROM delivery_items').delivered_quantity,1);for(const date of ['2027-01-08','2027-01-15','2027-01-22'])await deliver(date);assert.equal(one('SELECT status FROM subscription_packages WHERE order_id=?',order.order.id).status,'open');const last=await deliver('2027-01-29');assert.equal(last.preparation[0].total_quantity,1);assert.equal(one('SELECT status FROM subscription_packages').status,'completed');assert.equal(one("SELECT COUNT(*) n FROM outbox WHERE topic='fiscal.final.requested'").n,1);});
test('Q060: replay with changed partial quantity cannot silently succeed',async()=>{await buy();at('2027-01-01T10:00:00Z');const delivery=(await generate()).orders[0],body={action:'complete',id:delivery.id,status:'delivered',items:delivery.items.map(item=>({id:item.id,deliveredQuantity:1}))};ok(await api('/api/admin/deliveries',body,{admin:true}));ok(await api('/api/admin/deliveries',{...body,items:body.items.map(item=>({...item,deliveredQuantity:2}))},{admin:true}),409);});
test('Q140 Q141: stock reserves FEFO, blocks overselling and consumes only handed units',async()=>{ok(await api('/api/admin/products/prod_kravlje_1l',{inventoryEnabled:true},{admin:true,method:'PATCH'}));await api('/api/admin/inventory',{productId:'prod_kravlje_1l',lotNumber:'A',expiresOn:'2027-02-01',quantity:8},{admin:true});await buy();ok(await api('/api/checkout',payload()),409);assert.equal(one('SELECT reserved FROM inventory_lots').reserved,8);await deliver('2027-01-01');assert.deepEqual({...one('SELECT quantity,reserved FROM inventory_lots')},{quantity:6,reserved:6});});
test('Q141: expired or short-lived stock cannot cover a prepaid package',async()=>{ok(await api('/api/admin/products/prod_kravlje_1l',{inventoryEnabled:true},{admin:true,method:'PATCH'}));ok(await api('/api/admin/inventory',{productId:'prod_kravlje_1l',lotNumber:'BAD',expiresOn:'2026-12-29',quantity:8},{admin:true}),422);ok(await api('/api/admin/inventory',{productId:'prod_kravlje_1l',lotNumber:'SHORT',expiresOn:'2027-01-03',quantity:8},{admin:true}),201);ok(await api('/api/checkout',payload()),409);assert.equal(count('orders'),0);});
test('Q069: refund request freezes preparation; mock approval returns only remaining net goods',async()=>{const paid=await buy();await deliver('2027-01-01');const preview=ok(await api('/api/admin/refunds?orderId='+paid.order.id,undefined,{admin:true}));assert.equal(preview.amountMinor,120000);const request=ok(await api('/api/admin/refunds',{action:'request',orderId:paid.order.id,reason:'Preostala količina',idempotencyKey:'refund-case-001'},{admin:true}));assert.equal((await generate('2027-01-08')).orders.length,0);const approved=ok(await api('/api/admin/refunds',{id:request.id,expectedVersion:1,action:'approve'},{admin:true}));assert.equal(approved.status,'approved');const completed=ok(await api('/api/admin/refunds',{id:request.id,expectedVersion:2,action:'execute'},{admin:true}));assert.equal(completed.status,'completed');assert.match(completed.payment_reference,/^MOCK-/);assert.equal(one('SELECT cancelled_quantity FROM package_lines').cancelled_quantity,6);});
test('Q069: live refund remains approved until bank and fiscal adapters are connected',async()=>{const paid=await buy();const r=ok(await api('/api/admin/refunds',{action:'request',orderId:paid.order.id,reason:'Test',idempotencyKey:'refund-case-002'},{admin:true}));ok(await api('/api/admin/refunds',{id:r.id,expectedVersion:1,action:'approve'},{admin:true}));env.PAYMENT_MODE='disabled';ok(await api('/api/admin/refunds',{id:r.id,expectedVersion:2,action:'execute'},{admin:true}),503);assert.equal(one('SELECT status FROM refund_requests').status,'approved');assert.equal(one('SELECT payment_status FROM orders').payment_status,'paid');});
test('Q091 Q092: named staff roles enforce server permissions and record personal actor',async()=>{env.ADMIN_EMAIL='owner@example.test';env.ADMIN_PASSWORD='owner-long-password';const owner=ok(await api('/api/admin/access',{email:env.ADMIN_EMAIL,password:env.ADMIN_PASSWORD}));const headers={Authorization:'Bearer '+owner.sessionToken};const person=ok(await api('/api/admin/staff',{email:'manager@example.test',fullName:'Menadžer',password:'manager-password-long',role:'manager'},{headers})).staff;assert.equal(person.role,'manager');const manager=ok(await api('/api/admin/access',{email:'manager@example.test',password:'manager-password-long'}));const mh={Authorization:'Bearer '+manager.sessionToken};ok(await api('/api/admin/products/prod_kravlje_1l',{name:'Lično izmenjeno'},{method:'PATCH',headers:mh}));assert.equal(one("SELECT actor_id FROM audit_log WHERE action='product.updated'").actor_id,'manager@example.test');ok(await api('/api/admin/staff',undefined,{headers:mh}),403);ok(await api('/api/admin/staff',{id:person.id,isActive:false},{headers}));ok(await api('/api/admin/products',undefined,{headers:mh}),403);});
test('Q091: driver may read routes but cannot access customer database or change prices',async()=>{env.ADMIN_EMAIL='owner@example.test';env.ADMIN_PASSWORD='owner-long-password';const owner=ok(await api('/api/admin/access',{email:env.ADMIN_EMAIL,password:env.ADMIN_PASSWORD}));ok(await api('/api/admin/staff',{email:'driver@example.test',fullName:'Vozač',password:'driver-password-long',role:'driver'},{headers:{Authorization:'Bearer '+owner.sessionToken}}));const driver=ok(await api('/api/admin/access',{email:'driver@example.test',password:'driver-password-long'}));const headers={Authorization:'Bearer '+driver.sessionToken};ok(await api('/api/admin/customers',undefined,{headers}),403);ok(await api('/api/admin/products/prod_kravlje_1l',{priceMinor:1},{method:'PATCH',headers}),403);ok(await api('/api/admin/deliveries?date=2027-01-01',undefined,{headers}));});
test('Q060: partial one-time delivery carries only remaining units without another charge',async()=>{const paid=await buy([line('one_time','weekly',3)]);at('2027-01-01T10:00:00Z');const route=await generate();const d=route.orders[0];ok(await api('/api/admin/deliveries',{action:'complete',id:d.id,status:'delivered',items:d.items.map(i=>({id:i.id,deliveredQuantity:1}))},{admin:true}));const order=one('SELECT * FROM orders WHERE id=?',paid.order.id);assert.equal(order.fulfillment_status,'planned');const next=await deliver(order.delivery_date);assert.equal(next.preparation[0].total_quantity,2);assert.equal(one('SELECT fulfillment_status FROM orders WHERE id=?',paid.order.id).fulfillment_status,'delivered');assert.equal(count('orders'),1);});
test('Q046: extending pause cannot reset its three-month maximum',async()=>{const p=await buy();ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-02-01'}));at('2027-01-10T10:00:00Z');ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-04-05'}),422);assert.equal(one('SELECT pause_until FROM subscriptions').pause_until,'2027-02-01');});
test('Q143: scheduled holiday is omitted from package dates and consumes no entitlement',async()=>{await setting({holidays:['2027-01-08']});const q=ok(await quote({items:[line()]}));assert.deepEqual(q.lines[0].deliveryDates,['2027-01-01','2027-01-15','2027-01-22','2027-01-29']);await buy();await deliver('2027-01-01');assert.equal(one('SELECT next_delivery_date FROM subscriptions').next_delivery_date,'2027-01-15');assert.equal((await generate('2027-01-08')).orders.length,0);});
test('Q067: failed payment gets bounded retries and successful retry is idempotent',async()=>{const paid=await buy();db.raw.prepare("UPDATE orders SET payment_status='failed' WHERE id=?").run(paid.order.id);const pending=ok(await api('/api/admin/payments',{action:'retry',orderId:paid.order.id},{admin:true}));assert.equal(pending.status,'pending');ok(await api('/api/admin/payments',{action:'process'},{admin:true}));assert.equal(one('SELECT status FROM payment_attempts').status,'paid');ok(await api('/api/admin/payments',{action:'process'},{admin:true}));assert.equal(count('payment_attempts'),1);});
test('Q067: declined card retries stop after three attempts',async()=>{const p=await buy();db.raw.prepare("UPDATE orders SET payment_status='failed' WHERE id=?").run(p.order.id);db.raw.exec("UPDATE subscriptions SET payment_provider_ref='mock-decline'");ok(await api('/api/admin/payments',{action:'retry',orderId:p.order.id},{admin:true}));for(const date of ['2026-12-30T10:00:00Z','2027-01-01T10:00:00Z','2027-01-04T10:00:00Z']){at(date);ok(await api('/api/admin/payments',{action:'process'},{admin:true}));}assert.equal(one('SELECT attempts FROM payment_attempts').attempts,3);assert.equal(one('SELECT status FROM payment_attempts').status,'failed');assert.equal(one('SELECT payment_status FROM orders').payment_status,'failed');});
test('Q090: forged email delivery webhook cannot change message status',async()=>{env.RESEND_WEBHOOK_SECRET='whsec_'+Buffer.alloc(32,9).toString('base64');ok(await api('/api/webhooks/email',{type:'email.delivered',created_at:new Date().toISOString(),data:{email_id:'fake'}}),401);assert.equal(count('message_webhook_events'),0);});
test('Q090: signed email delivery is recorded once; older callbacks cannot downgrade it',async()=>{const {Webhook}=await import('svix');const secret='whsec_'+Buffer.alloc(32,9).toString('base64');env.RESEND_WEBHOOK_SECRET=secret;db.raw.exec("INSERT INTO message_deliveries(id,channel,recipient,provider,provider_reference,status) VALUES('message-test','email','audit@example.test','resend','email-test','accepted')");const send=async(type,time,id)=>{const body={type,created_at:time,data:{email_id:'email-test'}},timestamp=String(Math.floor(Date.now()/1000)),signature=new Webhook(secret).sign(id,new Date(),JSON.stringify(body));return api('/api/webhooks/email',body,{headers:{'svix-id':id,'svix-timestamp':timestamp,'svix-signature':signature}});};ok(await send('email.delivered','2026-12-30T10:00:00Z','evt1'));ok(await send('email.sent','2026-12-30T09:59:00Z','evt2'));ok(await send('email.delivered','2026-12-30T10:00:00Z','evt1'));assert.equal(one("SELECT status FROM message_deliveries WHERE id='message-test'").status,'delivered');assert.equal(count('message_webhook_events'),2);});
test('Q089: opted-in SMS is a separate durable message and revocation suppresses future SMS',async()=>{const p=await buy();const c=one('SELECT id FROM customers');db.raw.prepare("INSERT INTO customer_credentials(customer_id,password_hash,email_verified_at,whatsapp_phone,whatsapp_verified_at) VALUES(?,'unused','2026-12-30','+381600000000','2026-12-30')").run(c.id);env.SMS_MODE='mock';ok(await api('/api/account',{smsNotifications:true},{method:'PATCH',cookie:cookie()}));ok(await mutate(p.subscription.id,'skip_next'));ok(await api('/api/admin/integrations',{action:'process'},{admin:true}));assert.equal(one("SELECT COUNT(*) n FROM message_deliveries WHERE channel='sms' AND status='simulated'").n,1);ok(await api('/api/account',{smsNotifications:false},{method:'PATCH',cookie:cookie()}));ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-02-01'}));ok(await api('/api/admin/integrations',{action:'process'},{admin:true}));assert.equal(one("SELECT COUNT(*) n FROM message_deliveries WHERE channel='sms'").n,1);});
test('Q096: reconciled historical units reduce remaining quantity without duplicate charge',async()=>{const p=await buy();db.raw.exec('DELETE FROM package_lines; DELETE FROM subscription_packages;');const item=one('SELECT id FROM order_items');ok(await api('/api/admin/legacy',{orderId:p.order.id,nextDeliveryDate:'2027-01-08',advanceInvoiceNumber:'EXISTING-PFR',advanceTime:'2026-12-30T10:00:00Z',confirmed:true,lines:[{id:item.id,deliveredQuantity:2}]},{admin:true}));assert.equal(one('SELECT imported_delivered_quantity FROM package_lines').imported_delivered_quantity,2);for(const date of ['2027-01-08','2027-01-15','2027-01-22'])await deliver(date);assert.equal(one('SELECT status FROM subscription_packages').status,'completed');assert.equal(count('orders'),1);assert.equal(count('legacy_reconciliations'),1);});
test('Q141: expired reservation blocks handover and can be exchanged for valid inventory',async()=>{ok(await api('/api/admin/products/prod_kravlje_1l',{inventoryEnabled:true},{admin:true,method:'PATCH'}));ok(await api('/api/admin/inventory',{productId:'prod_kravlje_1l',lotNumber:'A',expiresOn:'2027-01-30',quantity:8},{admin:true}),201);const p=await buy();ok(await mutate(p.subscription.id,'pause',{pauseUntil:'2027-02-01'}));ok(await api('/api/admin/inventory',{productId:'prod_kravlje_1l',lotNumber:'B',expiresOn:'2027-05-01',quantity:8},{admin:true}),201);at('2027-02-05T10:00:00Z');const locked=(await generate('2027-02-05')).orders[0];ok(await api('/api/admin/deliveries',{action:'complete',id:locked.id,status:'delivered'},{admin:true}),409);ok(await api('/api/admin/inventory',{action:'replace',orderId:p.order.id},{admin:true}),201);assert.equal(one("SELECT reserved FROM inventory_lots WHERE lot_number='A'").reserved,0);assert.equal(one("SELECT reserved FROM inventory_lots WHERE lot_number='B'").reserved,8);await deliver('2027-02-05');assert.equal(one("SELECT quantity FROM inventory_lots WHERE lot_number='B'").quantity,6);});
test('Q069: account refund preview is scoped and contains no payment tokens',async()=>{const p=await buy();const result=ok(await api('/api/account/refunds?orderId='+p.order.id,undefined,{cookie:cookie()}));assert.deepEqual(Object.keys(result.order),['id']);await buy(undefined,{customer:customer({email:'different@example.test'})});const other=one("SELECT id FROM customers WHERE email='different@example.test'");ok(await api('/api/account/refunds?orderId='+p.order.id,undefined,{cookie:cookie(other.id)}),404);});
for(const quantity of [1,2,100])for(const cadence of ['weekly','biweekly'])for(const failFirst of [false,true])test(`Q060 Q190: conserved units quantity=${quantity} cadence=${cadence} initialFailure=${failFirst}`,async()=>{const paid=await buy([line('subscription',cadence,quantity)]);const required=quantity*(cadence==='weekly'?4:2);let handed=0,visits=0;let date='2027-01-01';while(handed<required&&visits<10){at(date+'T10:00:00Z');const route=await generate(date);assert.equal(route.orders.length,1);const d=route.orders[0];assert.equal(d.items[0].quantity,Math.min(quantity,required-handed));const fail=failFirst&&visits===0;const amount=fail?0:visits===(failFirst?1:0)&&quantity>1?quantity-1:Number(d.items[0].quantity);ok(await api('/api/admin/deliveries',{action:'complete',id:d.id,status:fail?'failed':'delivered',...(fail?{}:{items:[{id:d.items[0].id,deliveredQuantity:amount}]})},{admin:true}));handed+=amount;visits++;date=new RealDate(RealDate.parse(date+'T12:00:00Z')+(cadence==='weekly'?7:14)*86400000).toISOString().slice(0,10);assert.equal(one('SELECT status FROM subscription_packages WHERE order_id=?',paid.order.id).status,handed===required?'completed':'open');}assert.equal(handed,required);assert.equal(one("SELECT SUM(delivered_quantity) n FROM delivery_items").n,required);assert.equal(one("SELECT COUNT(*) n FROM outbox WHERE topic='fiscal.final.requested'").n,1);});
