"use client";

import { useLocalize, useLocale } from "@/app/lib/i18n/client";
import { useState } from 'react';
import { fetchJson,formatMoney } from '../lib/frontend';
type Row=Record<string,unknown>;
export function RefundRequest({orders}:{orders:Row[]}){
  const localize = useLocalize();
  const locale = useLocale();
 const [preview,setPreview]=useState<{order:{id:string};amountMinor:number;lines:{productName:string;remaining:number}[]}|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return localize(<details className="card"><summary>Zahtev za povraćaj preostalih proizvoda</summary><p>Možete zatražiti povraćaj neisporučenih proizvoda koji još nisu u pripremi. Dostava nije uključena u ovaj obračun. Zahtev proverava naš tim.</p><form onSubmit={async e=>{e.preventDefault();setMessage('');const v=new FormData(e.currentTarget);try{setPreview(await fetchJson(`/api/account/refunds?orderId=${encodeURIComponent(String(v.get('orderId')))}`));}catch(e){setMessage(e instanceof Error?e.message:'Provera nije uspela.');}}}><label className="field"><span>Moja porudžbina</span><select name="orderId" required><option value="">Izaberite porudžbinu</option>{orders.filter(o=>o.payment_status==='paid').map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.order_number)} · {formatMoney(Number(o.total_minor)/100, locale)}</option>)}</select></label><button className="button secondary">Proveri preostali iznos</button></form>{preview?<form onSubmit={async e=>{e.preventDefault();setBusy(true);const v=new FormData(e.currentTarget);try{await fetchJson('/api/account/refunds',{method:'POST',body:JSON.stringify({orderId:preview.order.id,reason:v.get('reason'),idempotencyKey:crypto.randomUUID()})});setMessage('Zahtev je primljen. Preostala priprema je zaustavljena dok tim ne obradi zahtev. Novac još nije vraćen.');setPreview(null);}catch(e){setMessage(e instanceof Error?e.message:'Zahtev nije poslat.');}finally{setBusy(false);}}}><p>Za razmatranje: <strong>{formatMoney(preview.amountMinor/100, locale)}</strong></p><ul>{preview.lines.map((line,i)=><li key={i}>{line.productName}: {line.remaining} komada</li>)}</ul><label className="field"><span>Razlog zahteva</span><textarea name="reason" maxLength={500} required /></label><button className="button" disabled={busy||!preview.amountMinor}>Pošalji zahtev i zaustavi pripremu</button></form>:null}{message?<p role="status">{message}</p>:null}</details>);
}
