ALTER TABLE products ADD COLUMN gallery_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE products ADD COLUMN ingredients TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN allergens TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN nutrition_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE products ADD COLUMN sale_price_minor INTEGER;
ALTER TABLE products ADD COLUMN sale_subscription_price_minor INTEGER;
ALTER TABLE products ADD COLUMN sale_starts_at TEXT;
ALTER TABLE products ADD COLUMN sale_ends_at TEXT;
ALTER TABLE products ADD COLUMN inventory_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN shipping_json TEXT;
ALTER TABLE orders ADD COLUMN billing_json TEXT;
ALTER TABLE orders ADD COLUMN slot_id TEXT;
ALTER TABLE subscriptions ADD COLUMN shipping_json TEXT;
ALTER TABLE subscriptions ADD COLUMN billing_json TEXT;
ALTER TABLE subscriptions ADD COLUMN slot_id TEXT;
ALTER TABLE promo_codes ADD COLUMN first_purchase_only INTEGER NOT NULL DEFAULT 0;
ALTER TABLE promo_codes ADD COLUMN per_customer_limit INTEGER;
ALTER TABLE promo_codes ADD COLUMN stackable INTEGER NOT NULL DEFAULT 0;
CREATE TABLE order_promotions (order_id TEXT NOT NULL REFERENCES orders(id), promo_id TEXT NOT NULL REFERENCES promo_codes(id), customer_id TEXT NOT NULL REFERENCES customers(id), discount_minor INTEGER NOT NULL CHECK(discount_minor >= 0), PRIMARY KEY(order_id,promo_id));
CREATE INDEX order_promotions_customer_idx ON order_promotions(promo_id,customer_id);
ALTER TABLE delivery_items ADD COLUMN delivered_quantity INTEGER CHECK(delivered_quantity IS NULL OR (delivered_quantity >= 0 AND delivered_quantity <= quantity));
ALTER TABLE package_lines ADD COLUMN cancelled_quantity INTEGER NOT NULL DEFAULT 0 CHECK(cancelled_quantity >= 0);
CREATE TABLE inventory_lots (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), lot_number TEXT NOT NULL, expires_on TEXT, quantity INTEGER NOT NULL CHECK(quantity >= 0), reserved INTEGER NOT NULL DEFAULT 0 CHECK(reserved >= 0 AND reserved <= quantity), version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(product_id,lot_number));
CREATE TABLE inventory_reservations (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), product_id TEXT NOT NULL REFERENCES products(id), lot_id TEXT NOT NULL REFERENCES inventory_lots(id), quantity INTEGER NOT NULL CHECK(quantity >= 0), consumed INTEGER NOT NULL DEFAULT 0 CHECK(consumed >= 0 AND consumed <= quantity), UNIQUE(order_id,lot_id));
CREATE TABLE inventory_movements (id TEXT PRIMARY KEY, lot_id TEXT NOT NULL REFERENCES inventory_lots(id), quantity INTEGER NOT NULL, reason TEXT NOT NULL, actor_id TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admin_users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, full_name TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','manager','driver','finance')), is_active INTEGER NOT NULL DEFAULT 1, version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE admin_sessions ADD COLUMN admin_user_id TEXT REFERENCES admin_users(id);
CREATE TABLE refund_requests (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), customer_id TEXT NOT NULL REFERENCES customers(id), status TEXT NOT NULL CHECK(status IN ('requested','approved','processing','completed','rejected','unknown')), amount_minor INTEGER NOT NULL CHECK(amount_minor > 0), items_json TEXT NOT NULL, reason TEXT NOT NULL, payment_reference TEXT, fiscal_reference TEXT, idempotency_key TEXT NOT NULL UNIQUE, version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX refund_active_order_idx ON refund_requests(order_id) WHERE status IN ('requested','approved','processing','unknown');
CREATE TABLE payment_attempts (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), operation TEXT NOT NULL CHECK(operation IN ('charge','refund')), status TEXT NOT NULL CHECK(status IN ('pending','processing','paid','failed','unknown')), amount_minor INTEGER NOT NULL, provider TEXT NOT NULL, provider_reference TEXT, idempotency_key TEXT NOT NULL UNIQUE, attempts INTEGER NOT NULL DEFAULT 0, next_attempt_at TEXT, last_error TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE message_deliveries (id TEXT PRIMARY KEY, outbox_id TEXT, channel TEXT NOT NULL, recipient TEXT NOT NULL, subject TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', provider TEXT NOT NULL, provider_reference TEXT, status TEXT NOT NULL DEFAULT 'queued', last_error TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX message_provider_idx ON message_deliveries(provider_reference);
CREATE TABLE legacy_reconciliations (id TEXT PRIMARY KEY, order_id TEXT NOT NULL UNIQUE REFERENCES orders(id), subscription_id TEXT NOT NULL REFERENCES subscriptions(id), details_json TEXT NOT NULL, actor_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
